### ISSUE TITLE
[Bug Report] 1.8 clients missing motd

### ISSUE THREAD

**Issue by PhanaticD** [jpenilla/MiniMOTD#53]
**Describe the bug**
pretty easy to reproduce, ping bungee with a 1.8.9 client and it is just empty

**To Reproduce**
ping server with this plugin on a 1.8.9 or older client

**Expected behavior**
motd to show

**Screenshots**
https://i.gyazo.com/9e1103accbee15d5570826f1f67abb7a.png

**Server Software and Version:**
[20:14:38 INFO]: This server is running Travertine version git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:8087b8f:175 by md_5

**Additional context**

**Comment by jpenilla** [comment]
This seems to be a bug with Travertine. I was unable to reproduce using the latest Waterfall, switching to Travertine caused the problem immediately. Please report this issue to Travertine. Here is the line where I set the motd: https://github.com/jpenilla/MiniMOTD/blob/b44070bdb0b553e8b71c24679da108fd9396d593/bungee/src/main/java/xyz/jpenilla/minimotd/bungee/PingListener.java#L85

**Comment by jpenilla** [comment]
After looking into it a bit more, the issue with Travertine is that it
1) Uses a separate gson instance for 1.7.2 client server pings
2) Converts server ping description components to legacy text for no reason on <=1.8 clients (Waterfall doesn't do this and server list pings from it work fine on 1.7.2+ clients)

Ideally this would be fixed in Travertine, but for now I found it easier to just include [a hack](https://github.com/jpenilla/MiniMOTD/commit/71f653122a8dc3a95338e735bc0b5874c26048ae) to workaround this weirdness. Will revisit if/when native Adventure support is added to Waterfall/Travertine.
