### ISSUE TITLE
[Bug Report] SLF4J lib in fabric 1.17

### ISSUE THREAD

**Issue by allanf181** [jpenilla/MiniMOTD#69]
**Describe the bug**
The latest version of MiniMOTD published contains the libs slf4j-api and log4j-slf4j-impl, causing conflicts.
In the code of this repository they have already been removed, publishing a new build would solve it.

**To Reproduce**
_Not applicable_ 

**Expected behavior**
_Not applicable_ 

**Screenshots**
![image](https://user-images.githubusercontent.com/14101716/123157233-a8cdff00-d440-11eb-8496-4075282daa2f.png)

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.17
 - Output of /version command: _Not applicable_ 

**Additional context**
https://github.com/BRForgers/DisFabric/issues/30

**Comment by jpenilla** [comment]
There is no 1.17 build released, you are attempting to run a build for 21w15a on 1.17 (so this issue is invalid). When I release a 1.17 build, it will obviously contain the changes for 1.17. Feel free to use a snapshot build from my CI until then: https://jenkins.jpenilla.xyz/job/MiniMOTD/lastSuccessfulBuild/

**Comment by aksulightning** [comment]
Please, release a development build 1.17 to CurseForge or inform. If users will download wrong version, by mistake. Thanks.
